// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.edu.um.domain;

import ar.com.edu.um.domain.NegocioDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NegocioDataOnDemand_Roo_Configurable {
    
    declare @type: NegocioDataOnDemand: @Configurable;
    
}
